name:                fmt-terminal-colors
version:             0.1.0.1
github:              "kfigiela/fmt-terminal-colors"
license:             BSD3
author:              "Kamil Figiela"
maintainer:          "kamil.figiela@gmail.com"
copyright:           "2018 Kamil Figiela"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ANSI terminal colors formatters for fmt library
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Extra formatters for fmt formatting library for colorful terminal output.

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- fmt

library:
  source-dirs: src

tests:
  fmt-terminal-colors-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fmt-terminal-colors
